server:
  port: 8085
spring:
  application:
    name: blockchain-integration-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
blockchain:
  ethereum:
    network-url: https://sepolia.infura.io/v3/YOUR_INFURA_PROJECT_ID
    private-key: YOUR_PRIVATE_KEY_HERE
    gas-limit: 4700000
