server:
  port: 8085

spring:
  application:
    name: blockchain-integration-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

blockchain:
  node-url: ${BLOCKCHAIN_NODE_URL:https://sepolia.infura.io/v3/YOUR_INFURA_PROJECT_ID}
  private-key: ${BLOCKCHAIN_PRIVATE_KEY:YOUR_PRIVATE_KEY_HERE}
  contract-address: ${RENTAL_CONTRACT_ADDRESS:0x5FbDB2315678afecb367f032d93F642f64180aa3}
  gas-limit: ${BLOCKCHAIN_GAS_LIMIT:4700000}
